// svelte/src/App.svelte
<script lang="ts">
    // import "./app.css";
    import { fetchData } from "./lib/index";
    import { CreateForm } from "./lib/CreateTodo";
    import { TodoList } from "./lib/Todo";
    import Toast from "./lib/Toast.svelte";
    import type { PbResponse, PostTodo, ToastStatus, Todo } from "./types";
    
    let isModalOpen = false;
    let toastMessage = "";
    let toastStatus: ToastStatus;
    
    let todos: Todo[];
    fetchData<PbResponse<Todo>>("http://127.0.0.1:8090/api/collections/todos/records")
        .then((data) => {
        todos = data.items;
        return data;
    });
        
        function openModal() {
            isModalOpen = true;
        }
        
        function closeModal() {
            isModalOpen = false;
        }
        
        async function deleteTodo(event: CustomEvent<string>) {
            try {
                const todoId = event.detail;
                await fetchData<Todo>(`http://127.0.0.1:8090/api/collections/todos/records/${todoId}`, {
                    method: "DELETE",
                });
                todos = todos.filter(t => t.id !== todoId);
                toastMessage = "Todo deleted!";
                toastStatus = "daisy-alert-success";
            } catch (err) {
                console.log(err);
                toastMessage = "Something went wrong while updating the todo..";
                toastStatus = "daisy-alert-error";
            }
        }

        async function addTodo(event: CustomEvent<PostTodo>) {
            try {
                const todo = event.detail;
                
                const data = await fetchData<Todo>("http://127.0.0.1:8090/api/collections/todos/records", {
                    method: "POST",
                    body: JSON.stringify(todo),
                    headers: {
                        "Content-Type": "application/json",
                    },
                });
                todos = [...todos, data];
                closeModal();
                toastMessage = "Todo added!";
                toastStatus = "daisy-alert-success";
            } catch (err) {
                console.log(err);
                toastMessage = "Something went wrong while adding the todo..";
                toastStatus = "daisy-alert-error";
            }
        }
        
        async function toggleTodoComplete(event: CustomEvent<string>) {
            try {
                const todoId = event.detail;
                const todo = todos.find(t => t.id === todoId);
                if(!todo) {
                    toastMessage = `could not find todo with id ${todoId}`;
                    toastStatus = "daisy-alert-error";
                    return;
                }
                const newCompleted = !todo.completed;
                
                await fetchData<Todo>(`http://127.0.0.1:8090/api/collections/todos/records/${todoId}`, {
                    method: "PATCH",
                    body: JSON.stringify({
                        completed: newCompleted,
                    }),
                    headers: {
                        "Content-Type": "application/json",
                    },
                });
                
                todos = todos.map((t) => {
                    if(t.id === todoId) {
                        t.completed = newCompleted;
                    }
                    return t;
                });
                
                toastMessage = "Todo updated!";
                toastStatus = "daisy-alert-success";
            } catch (err) {
                console.error(err);
                toastMessage = "Something went wrong while updating the todo..";
                toastStatus = "daisy-alert-error";
            }
        }
    </script>
    
    <main class="flex flex-col justify-center items-center mx-auto mt-10">
        <div>
            <button class="daisy-btn daisy-btn-lg daisy-btn-success" on:click={openModal}>Add todo +</button>
        </div>
        
        
        <!-- Open the modal using ID.showModal() method -->
        <TodoList {todos} on:toggle-todo={toggleTodoComplete} on:delete-todo={deleteTodo}/>
        <CreateForm
            isOpen={isModalOpen}
            on:close-create-todo-modal={closeModal}
            on:add-todo={addTodo}
        />

        {#if toastMessage && toastStatus}
            <Toast bind:message={toastMessage} bind:status={toastStatus} />
        {/if}
    </main>

// react/src/App.tsx
import { useState, useEffect } from 'react'
import './App.css'
import { PbResponse, PostTodo, ToastStatus, Todo } from './types';
import Toast from './components/Toast';
import TodoList from './components/TodoList';
import { CreateForm } from './components/CreateTodo';
import { fetchData } from './components';

function App() {

    const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
    const [todos, setTodos] = useState<Todo[]>([]);
    const [toastMessage, setToastMessage] = useState<string>("");
    const [toastStatus, setToastStatus] = useState<ToastStatus>("daisy-alert-success");

    function openModal() {
        setIsModalOpen(true);
    }
    function closeModal() {
        setIsModalOpen(false);

    }

    async function toggleTodoComplete(todoId: string) {
        try {
            const todo = todos.find(t => t.id === todoId);
            if (!todo) {
                setToastMessage(`could not find todo with id ${todoId}`);
                setToastStatus("daisy-alert-error");
                return;
            }
            const newCompleted = !todo.completed;

            await fetchData<Todo>(`http://127.0.0.1:8090/api/collections/todos/records/${todoId}`, {
                method: "PATCH",
                body: JSON.stringify({
                    completed: newCompleted,
                }),
                headers: {
                    "Content-Type": "application/json",
                },
            });

            setTodos(prevState => prevState.map((t) => {
                if (t.id === todoId) {
                    t.completed = newCompleted;
                }
                return t;
            }));

            setToastMessage("Todo updated!");
            setToastStatus("daisy-alert-success");
        } catch (err) {
            console.error(err);
            setToastMessage("Something went wrong while updating the todo..");
            setToastStatus("daisy-alert-error");
        }
    }

    async function addTodo(todo: PostTodo) {
        try {
            const data = await fetchData<Todo>("http://127.0.0.1:8090/api/collections/todos/records", {
                method: "POST",
                body: JSON.stringify(todo),
                headers: {
                    "Content-Type": "application/json",
                },
            });
            if (!data) {
                setToastMessage("Something went wrong while adding the todo..");
                setToastStatus("daisy-alert-error");
                return;
            }
            setTodos((prevState) => [...prevState, data]);
            closeModal();
            setToastMessage("Todo added!");
            setToastStatus("daisy-alert-success");
        } catch (err) {
            console.log(err);
            setToastMessage("Something went wrong while adding the todo..");
            setToastStatus("daisy-alert-error");
        }

    }

    async function deleteTodo(todoId: string) {
        try {
            await fetchData<Todo>(`http://127.0.0.1:8090/api/collections/todos/records/${todoId}`, {
                method: "DELETE",
            });
            setTodos((prevState) => prevState.filter(t => t.id !== todoId));
            setToastMessage("Todo deleted!");
            setToastStatus("daisy-alert-success");
        } catch (err) {
            console.log(err);
            setToastMessage("Something went wrong while updating the todo..");
            setToastStatus("daisy-alert-error");
        }
    }

    useEffect(() => {
        fetchData<PbResponse<Todo>>("http://127.0.0.1:8090/api/collections/todos/records")
            .then((data) => {
                const todos = data?.items;
                if (todos) {
                    setTodos(todos);
                }
            });
    }, []);

    return (
        <main className="flex flex-col justify-center items-center mx-auto mt-10">
            <div>
                <button className="daisy-btn daisy-btn-lg daisy-btn-success" onClick={openModal}>Add todo +</button>
            </div>


            <TodoList todos={todos} onToggleTodo={toggleTodoComplete} onDeleteTodo={deleteTodo} />
            <CreateForm
                isOpen={isModalOpen}
                onCloseCreateTodoModal={closeModal}
                onAddTodo={addTodo}
            />

            {toastMessage && toastStatus &&
                <Toast message={toastMessage} status={toastStatus} />
            }
        </main>

    )
}

export default App
