// react/src/components/Toast.tsx
import { ToastStatus } from "../types";
import { useEffect } from "react";

type Props = {
    status: ToastStatus;
    message: string;
    autoHide?: number;
}
export default function Toast({ status, message, autoHide = 2500 }: React.PropsWithChildren<Props>) {
    useEffect(() => {
        setTimeout(() => {
            status = "daisy-alert-success";
            message = "";
        }, autoHide);
    }, []);

    return (
        status && message &&
        <div className="daisy-toast daisy-toast-right daisy-toast-bottom">
            <div className={`daisy-alert daisy-alert-info ${status}`}>
                <span>{message}</span>
            </div>
        </div>
    );
}

// sveltekit/src/lib/Toast.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import type { ToastStatus } from "$lib/types";

    export let status: ToastStatus | undefined = "daisy-alert-success";
    export let message: string;
    export let autoHide = 2500;


    onMount(() => {
        setTimeout(() => {
            status = "daisy-alert-success";
            message = "";
        }, autoHide);
    });
</script>


{#if status && message}
    <div class="daisy-toast daisy-toast-right daisy-toast-bottom">
        <div class={`daisy-alert daisy-alert-info ${status}`}>
            <span>{message}</span>
        </div>
    </div>
{/if}
