// sveltekitJsdoc/src/lib/Toast.svelte
<script>
    import { onMount } from "svelte";


    /** @type {import("$lib/types").ToastStatus} */
    export let status = "daisy-alert-success";
    /**@type {string}*/
    export let message;
    /**@type {number}*/
    export let autoHide = 2500;


    onMount(() => {
        setTimeout(() => {
            status = "daisy-alert-success";
            message = "";
        }, autoHide);
    });
</script>


{#if status && message}
    <div class="daisy-toast daisy-toast-right daisy-toast-bottom">
        <div class={`daisy-alert daisy-alert-info ${status}`}>
            <span>{message}</span>
        </div>
    </div>
{/if}

// react/src/components/Toast.tsx
import { ToastStatus } from "../types";
import { useEffect } from "react";

type Props = {
    status: ToastStatus;
    message: string;
    autoHide?: number;
}
export default function Toast({ status, message, autoHide = 2500 }: React.PropsWithChildren<Props>) {
    useEffect(() => {
        setTimeout(() => {
            status = "daisy-alert-success";
            message = "";
        }, autoHide);
    }, []);

    return (
        status && message &&
        <div className="daisy-toast daisy-toast-right daisy-toast-bottom">
            <div className={`daisy-alert daisy-alert-info ${status}`}>
                <span>{message}</span>
            </div>
        </div>
    );
}
